### ISSUE TITLE
BUG: flake8heavened just runs flake8 in VSCode

### ISSUE THREAD

**Issue by bvidosits** [flakeheaven/flakeheaven#127] opened 2022-07-26 16:33 UTC
**Checklist**

* [x] Same issue occurs when reproducing the MWE below: new virtualenv, clean folder, minimal additional libs, etc.
* [ ] Same issue occurs when running without cache (eg by setting the env var `FLAKEHEAVEN_CACHE_TIMEOUT=0`)

**Bug Description**

According to the documentation [here](https://flakeheaven.readthedocs.io/en/latest/ide.html), these steps should integrate flakeheaven with my IDE (in my case vscode):

> 1. Open Flake8 plugin settings in your IDE.
> 2. Find something like “Executable Path”
> 3. Put `flake8heavened` in this field.

Linting does run, however all configurations are ignored. I suspect that something like `flake8 ${file}`, please see "additional context" at the bottom for the reasoning.

**Expected behavior**

Lint with the given `pyproject.toml` configurations.

**Bug Repro**

1. OS, arch
2. `python --version`
3. `pyproject.toml` (and / or all other config files that apply, eg `.pylintrc`, stc)
5. `pip freeze`
6.  `flakeheaven plugins`
7. Contents of any additional files (eg sample `.py` file(s) to be linted)
8. Any additional env vars setup
9. [If available] contents of `flakeheaven config -vvv`

---

1. macOS 12.4 21F79 x86_64
2. Python 3.10.5
3. Tested with minimal configuration:
```toml
[tool.flakeheaven]
format = "grouped"
max_line_length = 88
show_source = true

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-E203", "-E501", "-W503"]
```
5. Please see above
6.  Please see above
7. Single line that reaches 80 chars should suffice. (`line too long (81 > 79 characters)flake8(E501)` shows that both the `"-E501"` and `max_line_length = 88` are ignored along with everything else)
8. No need
9. N/A

1. create empty dir
2. create venv
3. install flakeheaven
4. configure flakeheaven in pyproject.toml as above
5. open dir via vscode
6. configure vscode to use the venv and lint with flakeheaven
7. create file with a single line that exceeds 80 chars

**Additional context**

- Running `flake8heavened` in the terminal uses correct configuration.
- Plugins not enabled in the config are still run, for example, if I install `flake8-import-order` but I don't enable it, it's errors still show up in VSCode, therefore I suspect `flake8heavened` doesn't do anything in VSCode, it just runs `flake8`
- Targeting the config file via arguments in vscode's settings produces the same results
```
"python.linting.flake8Args": [
        "--config",
        "${workspaceFolder}/pyproject.toml",
    ],
```
- **workaround:** Specifying absolute path (`which flake8heavened`) uses correct configuration without any additional arguments needed
```
"python.linting.flake8Path": "/abs/path/to/project/.venv/bin/flake8heavened",
```

If this is intended, docs about could be more verbose/clear.

**Comment by pwoolvett** [comment] 2022-07-27 00:11
Thank you for your feedback.

The problem is vs code, which runs `python -m flake8` when the path is not absolute. See the attached issue for a related discussion.

Im closing this in favour of #32  to keep feedback in one place.

Note: PRs are always welcome!

**Closed by pwoolvett** 2022-07-27 00:11 UTC
Labels: bug, triage
